version: "3"
services:
  # 백엔드 서버
  chat-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - ./.env
    environment:
      - NODE_ENV=production
    networks:
      - chat-network

  # 프론트엔드
  react-app:
    build: .
    ports:
      - "80:80"
    depends_on:
      - chat-server
    networks:
      - chat-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  chat-network:
    driver: bridge 